require_relative 'system/boot'
require 'rom-sql'
require 'rom/sql/rake_task'

namespace :db do
  task :setup do
    Application.start(:persistence)
    ROM::SQL::RakeSupport.env = Application['persistence.container']
  end
end
