require_relative 'system/boot'
require 'rom-sql'
require 'rom/sql/rake_task'

namespace :db do
  task :setup do
    Application.start(:persistence)
    ROM::SQL::RakeSupport.env = Application['persistence.container']
  end
end

namespace :people do
  desc 'Import people from SalesLoft API'
  task :import do
    import_people = Application['operations.import_people']
    import_people.call
  end
end
